### ISSUE TITLE
Toogle Menu not functioning when you click submenus

### ISSUE THREAD

**Issue by austriamarcelo** [jbowyers/responsive-menu#1] opened 2015-04-27 07:07 UTC
![screenshot from 2015-04-27 15 05 36](https://cloud.githubusercontent.com/assets/6365156/7343043/e6e30aa0-ecee-11e4-9b23-c40812442132.png)
![screenshot from 2015-04-27 15 06 04](https://cloud.githubusercontent.com/assets/6365156/7343048/f5770260-ecee-11e4-9637-3a8f21725c0c.png)

**Comment by jbowyers** [comment] 2015-04-27 15:47
austriamarcelo can you privide more info about the issue. I am not clear what the issue is.

**Comment by austriamarcelo** [comment] 2015-05-07 02:16
I am noticing that sometimes when I click toggle menu then click the submenus and click again the toggle it doesn't open the item menu.  What could be going on here?  It works most of the time, but not consistently.

**Comment by jbowyers** [comment] 2015-05-07 03:20
Yes, thanks, I found the bug you are refering to. It seems to only happen in Firefox. I am working on fixing it.

**Comment by jbowyers** [comment] 2015-05-07 21:19
The bug is fixed in v0.1.7

**Closed as completed by jbowyers** 2015-05-07 21:19 UTC
